title: Yotils
description: Yotils is a utility library for TypeScript
theme: just-the-docs

url: https://behzadam.github.io/yotils/yotils.html

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template