title: Yotils
description: Yotils is a utility library for TypeScript
theme: just-the-docs

url: https://behzadam.github.io/yotils

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout